#!/usr/bin/env python3

import logging
from time import sleep

logging.basicConfig(level=logging.INFO)

i = 0
while(True):
	i+=1
	print(str(i))
	logging.info("info")
	logging.error("error")
	sleep(2)
